---

maintenance_global_exclude_tasks: []
maintenance_host_exclude_tasks: []
maintenance_exclude_tasks: "{{ maintenance_global_exclude_tasks + maintenance_host_exclude_tasks }}"

# Set the package manager to be either rpm, deb, etc. Needed to get apache binary name.
# rpm -> httpd
# anything else(deb, etc) -> apache2
package_manager: "rpm"

