---

dependency:
  name: galaxy
  options:
    ignore-errors: true
    role-file: requirements.yml
    requirements-file: requirements.yml

  # create directory structure so molecule can load the collection itself
  name: shell
  command: >-
    mkdir -p ${MOLECULE_EPHEMERAL_DIRECTORY}/collections/ansible_collections/adfinis &&
    ln -sfn ${PWD} ${MOLECULE_EPHEMERAL_DIRECTORY}/collections/ansible_collections/adfinis/maintenance

provisioner:
  name: ansible


driver:
  name: docker

platforms:
  - name: "maintenance-${image:-debian13}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${image:-debian13}-ansible:latest"
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_ROLES_PATH: "../../../roles"
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_EPHEMERAL_DIRECTORY}/collections"
  config_options:
    defaults:
      retry_files_enabled: false
      callbacks_enabled: "adfinis.maintenance.report"
      duplicate_dict_key: ignore
      inject_facts_as_vars: false

verifier:
  name: ansible
