---

- name: Molecule Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when:
        - ansible_facts.os_family == "Debian"

    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      when:
        - ansible_facts.os_family == "RedHat"

    - name: Install general packages
      ansible.builtin.package:
        name:
          - logrotate
          - openssh-server
          - postfix

    - name: Run logrotate once so status file exists
      ansible.builtin.command:
        cmd: logrotate /etc/logrotate.conf

    - name: SSH working directory
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: "0755"
        owner: root
        group: root
