---
- name: Install packages
  ansible.builtin.apt:
    name:
      - openssh-server
    state: present
    update_cache: true

- name: SSH working directory
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Security repo
  ansible.builtin.copy:
    content: |
      deb http://security.debian.org/debian-security buster/updates main
    dest: /etc/apt/sources.list.d/security_debian_org_debian_security.list
    mode: "0755"
    owner: root
    group: root
