---

- name: All tasks
  hosts: all
  gather_facts: true
  vars:
    maintenance_exclude_tasks:
      - 10-028
      - 10-032
      - 10-039
      - 10-041
      - 10-042
      - 10-051  # TODO: remove these!

  tasks:
    - name: "Include 10_linux/"
      ansible.builtin.include_role:
        name: "maintenance_10_linux"

    - name: "Include 11_debian/"
      ansible.builtin.include_role:
        name: "maintenance_11_debian"
      when: '"maintain-debian" in inventory_hostname'

    - name: "Include 15_rhel/"
      ansible.builtin.include_role:
        name: "maintenance_15_rhel"
      when: '"maintain-rhel" in inventory_hostname or "maintain-suse" in inventory_hostname'
