---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "${host_prefix}-${image:-debian10}-${tag:-latest}"
    image: "${namespace}${image}:${tag:-latest}"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      retry_files_enabled: false
      callbacks_enabled: "adfinis.maintenance.report"
      duplicate_dict_key: ignore
      inject_facts_as_vars: false


scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # TODO: - side-effects
    - idempotence
    - destroy

verifier:
  name: ansible
