---

- name: Prepare debian vm for tests to succeed
  hosts: all
  tasks:
    - name: Create aliases file
      ansible.builtin.lineinfile:
        line: "root: serverlogs@tux42.ch"
        dest: /etc/aliases
        state: present
        create: true
